Fix GPG key import issues
Issues come up when trying to import keys:

Logs:
```bash
+ rpmkeys --import /usr/share/distribution-gpg-keys/microsoft/microsoft.gpg
error: /usr/share/distribution-gpg-keys/microsoft/microsoft.gpg: import read failed(2).
```

```bash
+ rpmkeys --import /usr/share/distribution-gpg-keys/brave/brave-core.asc
warning: Certificate 0BB75829C2D4E821:
  The certificate is expired: The primary key is not live
```

Issue origin may possibly be changes to how Fedora serves the keys since F42 (?) (do not recall having mismatches back then).